/* ============================================================
   Tamasha SD — Board page
   Renders window.TAMASHA_BOARD (see board-data.js, which is
   generated by tools/build-board-photos.py).
   No dependencies, no build step.
   ============================================================ */
(function () {
  var seasons = window.TAMASHA_BOARD || [];
  var root = document.querySelector('[data-board]');
  if (!root) return;

  var reduceMotion = window.matchMedia('(prefers-reduced-motion: reduce)').matches;

  // Three tiers, in the order the board itself is structured.
  var TIERS = [
    {
      title: 'Directors',
      test: function (m) {
        return /^(director|executive-advisor|vp-)/.test(m.roleSlug);
      }
    },
    {
      title: 'Committee chairs',
      test: function (m) { return m.roleSlug !== 'intern'; }
    },
    {
      title: 'Interns',
      test: function (m) { return m.roleSlug === 'intern'; }
    }
  ];

  function seasonLabel(year) {
    var parts = year.split('-');
    return '20' + parts[0] + '\u2013' + parts[1];
  }

  function el(tag, cls, text) {
    var n = document.createElement(tag);
    if (cls) n.className = cls;
    if (text != null) n.textContent = text;
    return n;
  }

  // ---------------------------------------------------------
  // Lightbox
  // ---------------------------------------------------------
  var lb = {
    node: document.querySelector('.lightbox'),
    stage: document.querySelector('.lightbox-stage'),
    img: document.querySelector('.lightbox-stage img'),
    name: document.querySelector('.lb-name'),
    role: document.querySelector('.lb-role'),
    count: document.querySelector('.lb-count'),
    list: [],
    index: 0,
    opener: null
  };

  function stageWidth(ratio) {
    var h = lb.stage.getBoundingClientRect().height;
    var max = Math.min(1180, window.innerWidth * 0.92);
    return Math.min(h * ratio, max);
  }

  function show(i) {
    var m = lb.list[i];
    if (!m) return;
    lb.index = i;
    lb.name.textContent = m.name;
    lb.role.textContent = m.role;
    lb.count.textContent = i + 1 + ' of ' + lb.list.length;

    // Collapse to the tile crop, then widen once the full frame has loaded.
    if (!reduceMotion) lb.stage.style.width = '';
    lb.img.src = m.full;
    lb.img.alt = m.name + ' \u2014 ' + m.role;

    var widen = function () {
      var ratio = (lb.img.naturalWidth || 3) / (lb.img.naturalHeight || 4);
      lb.stage.style.width = stageWidth(ratio) + 'px';
    };
    if (lb.img.complete && lb.img.naturalWidth) {
      reduceMotion ? widen() : requestAnimationFrame(widen);
    } else {
      lb.img.onload = widen;
    }
  }

  function openLightbox(list, i, opener) {
    lb.list = list;
    lb.opener = opener || null;
    lb.node.hidden = false;
    requestAnimationFrame(function () { lb.node.classList.add('is-open'); });
    document.body.style.overflow = 'hidden';
    show(i);
    lb.node.querySelector('.lb-close').focus();
  }

  function closeLightbox() {
    lb.node.classList.remove('is-open');
    document.body.style.overflow = '';
    window.setTimeout(function () { lb.node.hidden = true; }, 250);
    if (lb.opener) lb.opener.focus();
  }

  function step(delta) {
    show((lb.index + delta + lb.list.length) % lb.list.length);
  }

  if (lb.node) {
    lb.node.querySelector('.lb-close').addEventListener('click', closeLightbox);
    lb.node.querySelector('.lb-prev').addEventListener('click', function () { step(-1); });
    lb.node.querySelector('.lb-next').addEventListener('click', function () { step(1); });
    lb.node.addEventListener('click', function (e) {
      if (e.target === lb.node) closeLightbox();
    });
    document.addEventListener('keydown', function (e) {
      if (lb.node.hidden) return;
      if (e.key === 'Escape') closeLightbox();
      else if (e.key === 'ArrowLeft') step(-1);
      else if (e.key === 'ArrowRight') step(1);
      else if (e.key === 'Tab') {
        // Keep focus inside the lightbox while it's open.
        var focusable = lb.node.querySelectorAll('button');
        var first = focusable[0];
        var last = focusable[focusable.length - 1];
        if (e.shiftKey && document.activeElement === first) {
          last.focus(); e.preventDefault();
        } else if (!e.shiftKey && document.activeElement === last) {
          first.focus(); e.preventDefault();
        }
      }
    });
    window.addEventListener('resize', function () {
      if (!lb.node.hidden && lb.img.naturalWidth) {
        lb.stage.style.width =
          stageWidth(lb.img.naturalWidth / lb.img.naturalHeight) + 'px';
      }
    });
  }

  // ---------------------------------------------------------
  // Reveal on scroll
  // ---------------------------------------------------------
  var observer = null;
  if (!reduceMotion && 'IntersectionObserver' in window) {
    document.documentElement.classList.add('js-reveal');
    observer = new IntersectionObserver(function (entries) {
      entries.forEach(function (entry) {
        if (!entry.isIntersecting) return;
        entry.target.classList.add('is-in');
        observer.unobserve(entry.target);
      });
    }, { rootMargin: '0px 0px -8% 0px' });
  }

  // ---------------------------------------------------------
  // Render
  // ---------------------------------------------------------
  function memberCard(m, list, i, delay) {
    var btn = el('button', 'member');
    btn.type = 'button';
    btn.setAttribute('aria-label', 'View photo of ' + m.name + ', ' + m.role);

    var frame = el('span', 'member-frame');
    var img = new Image();
    img.src = m.card;
    img.alt = '';
    img.width = 640;
    img.height = 854;
    img.loading = 'lazy';
    img.decoding = 'async';
    frame.appendChild(img);

    btn.appendChild(frame);
    btn.appendChild(el('span', 'member-name', m.name));
    btn.appendChild(el('span', 'member-role', m.role));

    btn.addEventListener('click', function () { openLightbox(list, i, btn); });

    if (observer) {
      btn.style.transitionDelay = Math.min(delay, 300) + 'ms';
      observer.observe(btn);
    } else {
      btn.classList.add('is-in');
    }
    return btn;
  }

  function renderGroupShot(season) {
    var wrap = el('div', 'group-shot');
    if (!season.groups.length) return null;

    var imgs = season.groups.map(function (src, i) {
      var im = new Image();
      im.src = src;
      im.alt = 'The ' + seasonLabel(season.year) + ' Tamasha SD board';
      im.loading = i === 0 ? 'eager' : 'lazy';
      if (i === 0) im.classList.add('is-shown');
      wrap.appendChild(im);
      return im;
    });

    var cap = el('div', 'group-caption');
    cap.innerHTML = 'The board <span>' + seasonLabel(season.year) + '</span>';
    wrap.appendChild(cap);

    if (imgs.length > 1) {
      var picker = el('div', 'group-picker');
      picker.setAttribute('role', 'group');
      picker.setAttribute('aria-label', 'Choose a board photo');
      imgs.forEach(function (im, i) {
        var dot = el('button', 'group-dot');
        dot.type = 'button';
        dot.setAttribute('aria-label', 'Board photo ' + (i + 1));
        dot.setAttribute('aria-pressed', i === 0 ? 'true' : 'false');
        dot.addEventListener('click', function () {
          imgs.forEach(function (other, j) {
            other.classList.toggle('is-shown', i === j);
          });
          picker.querySelectorAll('.group-dot').forEach(function (d, j) {
            d.setAttribute('aria-pressed', i === j ? 'true' : 'false');
          });
        });
        picker.appendChild(dot);
      });
      wrap.appendChild(picker);
    }
    return wrap;
  }

  function renderSeason(season) {
    root.innerHTML = '';

    var group = renderGroupShot(season);
    if (group) root.appendChild(group);

    if (!season.members.length) {
      var empty = el('div', 'season-empty');
      empty.appendChild(el('h2', null, 'Photos are on the way'));
      var p = el('p');
      p.innerHTML = 'Drop headshots into <code>photos/board/' + season.year +
        '/</code> named <code>first-last_role.jpg</code>, then run ' +
        '<code>python3 tools/build-board-photos.py</code>.';
      empty.appendChild(p);
      root.appendChild(empty);
      return;
    }

    var remaining = season.members.slice();
    var order = [];
    TIERS.forEach(function (tier) {
      var picked = remaining.filter(tier.test);
      remaining = remaining.filter(function (m) { return picked.indexOf(m) === -1; });
      if (picked.length) order.push({ tier: tier, members: picked });
    });
    if (remaining.length) order.push({ tier: { title: 'Board' }, members: remaining });

    // Flat list so the lightbox can walk the whole season in display order.
    var flat = [];
    order.forEach(function (block) { flat = flat.concat(block.members); });

    var seen = 0;
    order.forEach(function (block) {
      var section = el('section', 'tier');
      var head = el('div', 'tier-head');
      head.appendChild(el('h2', null, block.tier.title));
      head.appendChild(el('span', 'rule'));
      head.appendChild(el('span', 'count', block.members.length));
      section.appendChild(head);

      var grid = el('div', 'board-grid');
      block.members.forEach(function (m, i) {
        grid.appendChild(memberCard(m, flat, seen + i, i * 35));
      });
      seen += block.members.length;

      section.appendChild(grid);
      root.appendChild(section);
    });
  }

  // ---------------------------------------------------------
  // Season tabs
  // ---------------------------------------------------------
  var bar = document.querySelector('.season-tabs');

  function selectSeason(i) {
    bar.querySelectorAll('.season-tab').forEach(function (t, j) {
      t.setAttribute('aria-selected', i === j ? 'true' : 'false');
      t.tabIndex = i === j ? 0 : -1;
    });
    renderSeason(seasons[i]);
  }

  if (!seasons.length) {
    root.innerHTML = '<div class="season-empty"><h2>No board photos yet</h2>' +
      '<p>Run <code>python3 tools/build-board-photos.py</code> to generate them.</p></div>';
    return;
  }

  if (seasons.length > 1 && bar) {
    seasons.forEach(function (season, i) {
      var tab = el('button', 'season-tab', seasonLabel(season.year));
      tab.type = 'button';
      tab.setAttribute('role', 'tab');
      tab.setAttribute('aria-selected', 'false');
      tab.addEventListener('click', function () { selectSeason(i); });
      bar.appendChild(tab);
    });
    bar.setAttribute('role', 'tablist');
    bar.addEventListener('keydown', function (e) {
      var tabs = Array.prototype.slice.call(bar.querySelectorAll('.season-tab'));
      var at = tabs.indexOf(document.activeElement);
      if (at < 0) return;
      var next = e.key === 'ArrowRight' ? at + 1 : e.key === 'ArrowLeft' ? at - 1 : -1;
      if (next < 0 || next >= tabs.length) return;
      tabs[next].focus();
      tabs[next].click();
      e.preventDefault();
    });
  } else if (bar) {
    bar.parentNode.style.display = 'none';
  }

  selectSeason(0);
})();
