// Generated by tools/build-board-photos.py — do not edit by hand.
// To add a season: drop photos into photos/board/<yy-yy>/ using the
// first-last_role.jpg convention, then re-run the script.
window.TAMASHA_BOARD = [
  {
    "year": "25-26",
    "groups": [
      "photos/board/25-26/web/full-board-1.webp",
      "photos/board/25-26/web/full-board-2.webp",
      "photos/board/25-26/web/full-board-3.webp"
    ],
    "members": [
      {
        "name": "Pranav Rapthadu",
        "role": "Director",
        "roleSlug": "director",
        "card": "photos/board/25-26/web/pranav-rapthadu-card.webp",
        "full": "photos/board/25-26/web/pranav-rapthadu-full.webp"
      },
      {
        "name": "Shambhavi Tyagi",
        "role": "Director",
        "roleSlug": "director",
        "card": "photos/board/25-26/web/shambhavi-tyagi-card.webp",
        "full": "photos/board/25-26/web/shambhavi-tyagi-full.webp"
      },
      {
        "name": "Tejas Mani",
        "role": "Director",
        "roleSlug": "director",
        "card": "photos/board/25-26/web/tejas-mani-card.webp",
        "full": "photos/board/25-26/web/tejas-mani-full.webp"
      },
      {
        "name": "Vira Prakhya",
        "role": "Director",
        "roleSlug": "director",
        "card": "photos/board/25-26/web/vira-prakhya-card.webp",
        "full": "photos/board/25-26/web/vira-prakhya-full.webp"
      },
      {
        "name": "Anagha Kamath",
        "role": "Head Liaison",
        "roleSlug": "head-liaison",
        "card": "photos/board/25-26/web/anagha-kamath-card.webp",
        "full": "photos/board/25-26/web/anagha-kamath-full.webp"
      },
      {
        "name": "Keiya Brahmbhatt",
        "role": "Head Liaison",
        "roleSlug": "head-liaison",
        "card": "photos/board/25-26/web/keiya-brahmbhatt-card.webp",
        "full": "photos/board/25-26/web/keiya-brahmbhatt-full.webp"
      },
      {
        "name": "Aaditya Pillai",
        "role": "Exhibition & Outreach",
        "roleSlug": "exhibition-and-outreach",
        "card": "photos/board/25-26/web/aaditya-pillai-card.webp",
        "full": "photos/board/25-26/web/aaditya-pillai-full.webp"
      },
      {
        "name": "Shreya Sadhwani",
        "role": "Exhibition & Outreach",
        "roleSlug": "exhibition-and-outreach",
        "card": "photos/board/25-26/web/shreya-sadhwani-card.webp",
        "full": "photos/board/25-26/web/shreya-sadhwani-full.webp"
      },
      {
        "name": "Avi Uppalapati",
        "role": "Judging",
        "roleSlug": "judging",
        "card": "photos/board/25-26/web/avi-uppalapati-card.webp",
        "full": "photos/board/25-26/web/avi-uppalapati-full.webp"
      },
      {
        "name": "Bhaavana Anna",
        "role": "Registration",
        "roleSlug": "registration",
        "card": "photos/board/25-26/web/bhaavana-anna-card.webp",
        "full": "photos/board/25-26/web/bhaavana-anna-full.webp"
      },
      {
        "name": "Sumukhi Tunuguntla",
        "role": "Registration",
        "roleSlug": "registration",
        "card": "photos/board/25-26/web/sumukhi-tunuguntla-card.webp",
        "full": "photos/board/25-26/web/sumukhi-tunuguntla-full.webp"
      },
      {
        "name": "Aayushi Gandhi",
        "role": "Logistics",
        "roleSlug": "logistics",
        "card": "photos/board/25-26/web/aayushi-gandhi-card.webp",
        "full": "photos/board/25-26/web/aayushi-gandhi-full.webp"
      },
      {
        "name": "Rithika Thummalapenta",
        "role": "Logistics",
        "roleSlug": "logistics",
        "card": "photos/board/25-26/web/rithika-thummalapenta-card.webp",
        "full": "photos/board/25-26/web/rithika-thummalapenta-full.webp"
      },
      {
        "name": "Arushi Patra",
        "role": "Tech",
        "roleSlug": "tech",
        "card": "photos/board/25-26/web/arushi-patra-card.webp",
        "full": "photos/board/25-26/web/arushi-patra-full.webp"
      },
      {
        "name": "Vrindha Prakash",
        "role": "Tech",
        "roleSlug": "tech",
        "card": "photos/board/25-26/web/vrindha-prakash-card.webp",
        "full": "photos/board/25-26/web/vrindha-prakash-full.webp"
      },
      {
        "name": "Miloni Dharod",
        "role": "Media",
        "roleSlug": "media",
        "card": "photos/board/25-26/web/miloni-dharod-card.webp",
        "full": "photos/board/25-26/web/miloni-dharod-full.webp"
      },
      {
        "name": "Naisha Nallakula",
        "role": "Media",
        "roleSlug": "media",
        "card": "photos/board/25-26/web/naisha-nallakula-card.webp",
        "full": "photos/board/25-26/web/naisha-nallakula-full.webp"
      },
      {
        "name": "Radha Sikaria",
        "role": "Hospitality",
        "roleSlug": "hospitality",
        "card": "photos/board/25-26/web/radha-sikaria-card.webp",
        "full": "photos/board/25-26/web/radha-sikaria-full.webp"
      },
      {
        "name": "Riti Nalumachu",
        "role": "Hospitality",
        "roleSlug": "hospitality",
        "card": "photos/board/25-26/web/riti-nalumachu-card.webp",
        "full": "photos/board/25-26/web/riti-nalumachu-full.webp"
      },
      {
        "name": "Shriya Sudini",
        "role": "Hospitality",
        "roleSlug": "hospitality",
        "card": "photos/board/25-26/web/shriya-sudini-card.webp",
        "full": "photos/board/25-26/web/shriya-sudini-full.webp"
      },
      {
        "name": "Nandita Valiveti",
        "role": "Social & Venue",
        "roleSlug": "social-venue",
        "card": "photos/board/25-26/web/nandita-valiveti-card.webp",
        "full": "photos/board/25-26/web/nandita-valiveti-full.webp"
      },
      {
        "name": "Rangshree Goraiya",
        "role": "Social & Venue",
        "roleSlug": "social-venue",
        "card": "photos/board/25-26/web/rangshree-goraiya-card.webp",
        "full": "photos/board/25-26/web/rangshree-goraiya-full.webp"
      },
      {
        "name": "Chinmay Swaminathan",
        "role": "Finance",
        "roleSlug": "finance",
        "card": "photos/board/25-26/web/chinmay-swaminathan-card.webp",
        "full": "photos/board/25-26/web/chinmay-swaminathan-full.webp"
      },
      {
        "name": "Harini Karthikeyan",
        "role": "Finance",
        "roleSlug": "finance",
        "card": "photos/board/25-26/web/harini-karthikeyan-card.webp",
        "full": "photos/board/25-26/web/harini-karthikeyan-full.webp"
      },
      {
        "name": "Zaara Sutarwala",
        "role": "Safety & Wellness",
        "roleSlug": "safety-and-wellness",
        "card": "photos/board/25-26/web/zaara-sutarwala-card.webp",
        "full": "photos/board/25-26/web/zaara-sutarwala-full.webp"
      },
      {
        "name": "Bhagya Arora",
        "role": "Intern",
        "roleSlug": "intern",
        "card": "photos/board/25-26/web/bhagya-arora-card.webp",
        "full": "photos/board/25-26/web/bhagya-arora-full.webp"
      },
      {
        "name": "Elisa Varghese",
        "role": "Intern",
        "roleSlug": "intern",
        "card": "photos/board/25-26/web/elisa-varghese-card.webp",
        "full": "photos/board/25-26/web/elisa-varghese-full.webp"
      },
      {
        "name": "Jay Gima",
        "role": "Intern",
        "roleSlug": "intern",
        "card": "photos/board/25-26/web/jay-gima-card.webp",
        "full": "photos/board/25-26/web/jay-gima-full.webp"
      },
      {
        "name": "Trisha Mani",
        "role": "Intern",
        "roleSlug": "intern",
        "card": "photos/board/25-26/web/trisha-mani-card.webp",
        "full": "photos/board/25-26/web/trisha-mani-full.webp"
      }
    ]
  },
  {
    "year": "24-25",
    "groups": [
      "photos/board/24-25/web/full-board-1.webp",
      "photos/board/24-25/web/full-board-2.webp",
      "photos/board/24-25/web/full-board-3.webp"
    ],
    "members": [
      {
        "name": "Shrika Kantala",
        "role": "Director",
        "roleSlug": "director",
        "card": "photos/board/24-25/web/shrika-kantala-card.webp",
        "full": "photos/board/24-25/web/shrika-kantala-full.webp"
      },
      {
        "name": "Jiya Patel",
        "role": "Executive Advisor",
        "roleSlug": "executive-advisor",
        "card": "photos/board/24-25/web/jiya-patel-card.webp",
        "full": "photos/board/24-25/web/jiya-patel-full.webp"
      },
      {
        "name": "Kritika Vedula",
        "role": "VP Internal",
        "roleSlug": "vp-internal",
        "card": "photos/board/24-25/web/kritika-vedula-card.webp",
        "full": "photos/board/24-25/web/kritika-vedula-full.webp"
      },
      {
        "name": "Khushi Vakil",
        "role": "VP External",
        "roleSlug": "vp-external",
        "card": "photos/board/24-25/web/khushi-vakil-card.webp",
        "full": "photos/board/24-25/web/khushi-vakil-full.webp"
      },
      {
        "name": "Maulin Shah",
        "role": "VP Finance",
        "roleSlug": "vp-finance",
        "card": "photos/board/24-25/web/maulin-shah-card.webp",
        "full": "photos/board/24-25/web/maulin-shah-full.webp"
      },
      {
        "name": "Pranav Rapthadu",
        "role": "Head Liaison",
        "roleSlug": "head-liaison",
        "card": "photos/board/24-25/web/pranav-rapthadu-card.webp",
        "full": "photos/board/24-25/web/pranav-rapthadu-full.webp"
      },
      {
        "name": "Tejas Mani",
        "role": "Head Liaison",
        "roleSlug": "head-liaison",
        "card": "photos/board/24-25/web/tejas-mani-card.webp",
        "full": "photos/board/24-25/web/tejas-mani-full.webp"
      },
      {
        "name": "Vatsala Swamy",
        "role": "Head Liaison",
        "roleSlug": "head-liaison",
        "card": "photos/board/24-25/web/vatsala-swamy-card.webp",
        "full": "photos/board/24-25/web/vatsala-swamy-full.webp"
      },
      {
        "name": "Shreya Srinivasan",
        "role": "Exhibition & Outreach",
        "roleSlug": "exhibition-and-outreach",
        "card": "photos/board/24-25/web/shreya-srinivasan-card.webp",
        "full": "photos/board/24-25/web/shreya-srinivasan-full.webp"
      },
      {
        "name": "Shriya Sudini",
        "role": "Exhibition & Outreach",
        "roleSlug": "exhibition-and-outreach",
        "card": "photos/board/24-25/web/shriya-sudini-card.webp",
        "full": "photos/board/24-25/web/shriya-sudini-full.webp"
      },
      {
        "name": "Vira Prakhya",
        "role": "Judging",
        "roleSlug": "judging",
        "card": "photos/board/24-25/web/vira-prakhya-card.webp",
        "full": "photos/board/24-25/web/vira-prakhya-full.webp"
      },
      {
        "name": "Karina Parikh",
        "role": "Media",
        "roleSlug": "media",
        "card": "photos/board/24-25/web/karina-parikh-card.webp",
        "full": "photos/board/24-25/web/karina-parikh-full.webp"
      },
      {
        "name": "Naisha Nallakula",
        "role": "Media",
        "roleSlug": "media",
        "card": "photos/board/24-25/web/naisha-nallakula-card.webp",
        "full": "photos/board/24-25/web/naisha-nallakula-full.webp"
      },
      {
        "name": "Ketki Chakradeo",
        "role": "Hospitality",
        "roleSlug": "hospitality",
        "card": "photos/board/24-25/web/ketki-chakradeo-card.webp",
        "full": "photos/board/24-25/web/ketki-chakradeo-full.webp"
      },
      {
        "name": "Sruti Mani",
        "role": "Hospitality",
        "roleSlug": "hospitality",
        "card": "photos/board/24-25/web/sruti-mani-card.webp",
        "full": "photos/board/24-25/web/sruti-mani-full.webp"
      },
      {
        "name": "Ishika Masani",
        "role": "Social & Venue",
        "roleSlug": "social-venue",
        "card": "photos/board/24-25/web/ishika-masani-card.webp",
        "full": "photos/board/24-25/web/ishika-masani-full.webp"
      },
      {
        "name": "Nithila Radj",
        "role": "Social & Venue",
        "roleSlug": "social-venue",
        "card": "photos/board/24-25/web/nithila-radj-card.webp",
        "full": "photos/board/24-25/web/nithila-radj-full.webp"
      },
      {
        "name": "Aastha Patel",
        "role": "Tech Logistics",
        "roleSlug": "tech-logistics",
        "card": "photos/board/24-25/web/aastha-patel-card.webp",
        "full": "photos/board/24-25/web/aastha-patel-full.webp"
      },
      {
        "name": "Annika Singh",
        "role": "Intern",
        "roleSlug": "intern",
        "card": "photos/board/24-25/web/annika-singh-card.webp",
        "full": "photos/board/24-25/web/annika-singh-full.webp"
      },
      {
        "name": "Jeevan Karandikar",
        "role": "Tech Logistics",
        "roleSlug": "tech-logistics",
        "card": "photos/board/24-25/web/jeevan-karandikar-card.webp",
        "full": "photos/board/24-25/web/jeevan-karandikar-full.webp"
      },
      {
        "name": "Manu Mittal",
        "role": "Tech Logistics",
        "roleSlug": "tech-logistics",
        "card": "photos/board/24-25/web/manu-mittal-card.webp",
        "full": "photos/board/24-25/web/manu-mittal-full.webp"
      },
      {
        "name": "Rangshree Goraiya",
        "role": "Intern",
        "roleSlug": "intern",
        "card": "photos/board/24-25/web/rangshree-goraiya-card.webp",
        "full": "photos/board/24-25/web/rangshree-goraiya-full.webp"
      },
      {
        "name": "Shambhavi Tyagi",
        "role": "Intern",
        "roleSlug": "intern",
        "card": "photos/board/24-25/web/shambhavi-tyagi-card.webp",
        "full": "photos/board/24-25/web/shambhavi-tyagi-full.webp"
      }
    ]
  }
];
